import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {AiOutlineHome, AiOutlineForm, AiOutlineCreditCard, AiOutlineCalendar, AiOutlineLaptop, AiOutlineBell, AiOutlineMail, AiOutlineSearch, AiOutlineCamera, AiOutlineVideoCamera, AiOutlineShareAlt, AiOutlineUsergroupAdd, AiOutlineLogout} from 'react-icons/ai'
import {BiMoon, BiPoll, BiSmile} from 'react-icons/bi'
import {FaThumbsUp, FaUserAlt, FaRegComment} from 'react-icons/fa'
import {FiSend} from 'react-icons/fi'
import User from '../public/user2.jpg'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='flex'>
        {/* Side Nav-Bar */}
        <div className='min-h-screen px-5 max-sm:px-3 max-sm:hidden'>
          <div className='h-screen flex flex-col justify-between pt-10'>
            <ul className='text-3xl mt-10'>
              <li className='m-5 p-2 rounded-lg hover:bg-blue-100 hover:text-blue-500 duration-300'><AiOutlineHome/></li>
              <li className='m-5 p-2 rounded-lg hover:bg-blue-100 hover:text-blue-500 duration-300'><AiOutlineCalendar/></li>
              <li className='m-5 p-2 rounded-lg hover:bg-blue-100 hover:text-blue-500 duration-300'><AiOutlineLaptop/></li>
              <li className='m-5 p-2 rounded-lg hover:bg-blue-100 hover:text-blue-500 duration-300'><AiOutlineCreditCard/></li>
              <li className='m-5 p-2 rounded-lg hover:bg-blue-100 hover:text-blue-500 duration-300'><AiOutlineForm/></li>
            </ul>
            <ul className='text-3xl'>
            <li className='m-5 p-2 rounded-lg hover:bg-blue-100 hover:text-blue-500 duration-300'><AiOutlineLogout/></li>
            </ul>
          </div>
        </div>

        <div className='flex-1'>
          <nav className='flex items-center justify-between py-4 shadow-2xl'>
            <div className='mx-10 flex items-center bg-white px-5 gap-2 text-gray-500 text-lg py-1 rounded-lg border-2 w-6/12'>
              <AiOutlineSearch/>
              <input type="text" placeholder='Search' className='focus:outline-none bg-transparent flex-1'/>
            </div>
            <div className='flex space-x-6 mx-10 items-center text-xl'>
              <AiOutlineBell/>
              <AiOutlineMail/>
              <div className='max-sm:hidden'>
              <h4>Mudassir</h4>
              </div>
              <div className='flex items-center gap-2'>
              <BiMoon/>
              <h4>Dark</h4>
              </div>

            </div>
          </nav>
          {/*------------ Main Body ------------- */}
          <div className='flex items-start max-sm:items-center justify-center flex-row max-sm:flex-col bg-gray-100'>


            {/* -------- Activities --------- */}
            <div className='flex flex-col space-x-5 min-h-full w-3/12 max-sm:w-8/12 p-5 mt-5 relative'>
              <div className=' flex flex-col rounded-t-lg '>

              <div className='border-2 rounded-t-lg bg-white'>
                <div className='h-16 bg-blue-700 rounded-t-lg'></div>

                <div className='text-center flex items-center justify-center flex-col p-5'>
                <FaUserAlt className='w-16 h-16 text-xl bg-slate-400 rounded-full p-4 absolute top-12'/>
                  <h2 className='text-lg font-bold pt-3'>Cooper</h2>
                  <p className='text-xs text-gray-400 font-semibold  py-1'>Information Technology Professional @Employee Forums</p>
                </div>

                <div className='flex items-center justify-around px-2'>
                  <div className='flex items-center justify-center flex-col'>
                    <h1 className='text-lg font-bold pb-1'>500</h1>
                    <p className='text-xs font-semibold text-gray-400'>Profile Views</p>
                  </div>
                  <div className='flex items-center justify-center flex-col'>
                    <h1 className='text-lg font-bold pb-1'>500</h1>
                    <p className='text-xs font-semibold text-gray-400'>Post Views</p>
                  </div>
                  <div className='flex items-center justify-center flex-col'>
                    <h1 className='text-lg font-bold pb-1'>500</h1>
                    <p className='text-xs font-semibold text-gray-400'>&nbsp; Request &nbsp;</p>
                  </div>
                </div>

                <div className='text-center my-2 p-5'>
                  <p className='text-xl text-gray-500 font-bold'>75%</p>
                <input type="range" value='75' className="w-full h-2 bg-green-500 rounded-lg appearance-none cursor-pointer "/>
                  <p className='text-xs text-gray-800 font-semibold pt-1'>Complete your Profile</p>
                </div>

            </div>
              <div className='text-center border-2 border-t-0 rounded-b-lg py-5 bg-white'>
                <h2 className='text-md font-semibold text-blue-700'>My Activity</h2>
              </div>
          

            {/* Forums */}
            <div className='flex flex-col my-10 w-12/12 bg-white shadow-lg border-2 rounded-lg'>
                <div className='flex flex-col'>
                  <h4 className='text-lg font-semibold py-3 px-4'>Your Forums</h4>
                  <div className='h-60 overflow-y-scroll'>
                  {/* Users */}
                  <div className='flex items-center gap-5 pl-4 mt-3'>
                    <FaUserAlt className='text-2xl'/>
                    <div>
                      <h4 className='text-md font-semibold'>Accounting</h4>
                      <p className='text-xs text-gray-500 font-semibold'>4 Members</p>
                    </div>
                  </div>

                  {/* Users */}
                  <div className='flex items-center gap-5 pl-4 mt-3'>
                    <FaUserAlt className='text-2xl'/>
                    <div>
                      <h4 className='text-md font-semibold'>Frontend development</h4>
                      <p className='text-xs text-gray-500 font-semibold'>8 Members</p>
                    </div>
                    
                  </div>

                  {/* Users */}
                  <div className='flex items-center gap-5 pl-4 mt-3 pb-3'>
                    <FaUserAlt className='text-2xl'/>
                    <div>
                      <h4 className='text-md font-semibold'>Backend Development</h4>
                      <p className='text-xs text-gray-500 font-semibold'>5 Members</p>
                    </div>
                    
                  </div>

                  {/* Users */}
                  <div className='flex items-center gap-5 pl-4 pb-3'>
                    <FaUserAlt className='text-2xl'/>
                    <div>
                      <h4 className='text-md font-semibold'>Animation</h4>
                      <p className='text-xs text-gray-500 font-semibold'>3 Members</p>
                    </div>
                    
                  </div>

                  {/* Users */}
                  <div className='flex items-center gap-5 pl-4 pb-3'>
                    <FaUserAlt className='text-2xl'/>
                    <div>
                      <h4 className='text-md font-semibold'>Administration</h4>
                      <p className='text-xs text-gray-500 font-semibold'>4 Members</p>
                    </div>
                    
                  </div>

                  {/* Users */}
                  <div className='flex items-center gap-5 pl-4 pb-3'>
                    <FaUserAlt className='text-2xl'/>
                    <div>
                      <h4 className='text-md font-semibold'>Media Analyst</h4>
                      <p className='text-xs text-gray-500 font-semibold'>12 Members</p>
                    </div>
                    
                  </div>

                  {/* Users */}
                  <div className='flex items-center gap-5 pl-4 pb-3'>
                    <FaUserAlt className='text-2xl'/>
                    <div>
                      <h4 className='text-md font-semibold'>Buisness development</h4>
                      <p className='text-xs text-gray-500 font-semibold'>3 Members</p>
                    </div>
                    
                  </div>
                </div>
              </div>
                <div className='flex items-center justify-center border-t-2 p-4'>
                  <p className='text-blue-500 mr-2 font-semibold'>View All</p>
                </div>
              </div>

            </div>
          </div>

          <div className='sm:hidden bg-white w-full fixed bottom-0'>
          <ul className='text-3xl flex items-center justify-around'>
            <li className='flex flex-col items-center m-5 rounded-lg hover:text-blue-500 duration-300'><AiOutlineHome/><p className='text-xl text-gray-400 text-bold hover:text-blue-500 duration-300'>Home</p></li>

            <li className='flex flex-col items-center m-5 rounded-lg hover:text-blue-500 duration-300'><AiOutlineCalendar/><p className='text-xl text-gray-400 text-bold hover:text-blue-500 duration-300'>Calendar</p></li>

            <li className='flex flex-col items-center m-5 rounded-lg hover:text-blue-500 duration-300'><AiOutlineLaptop/><p className='text-xl text-gray-400 text-bold hover:text-blue-500 duration-300'>Work</p></li>

            <li className='flex flex-col items-center m-5 rounded-lg hover:text-blue-500 duration-300'><AiOutlineUsergroupAdd/><p className='text-xl text-gray-400 text-bold hover:text-blue-500 duration-300'>Forums</p></li>

            <li className='flex flex-col items-center m-5 rounded-lg hover:text-blue-500 duration-300'><AiOutlineForm/><p className='text-xl text-gray-400 text-bold hover:text-blue-500 duration-300'>Connect</p></li>
          </ul>
        </div>


            {/* ----------- 2 Column -----------*/}
            <div className='flex flex-col w-6/12 max-sm:w-11/12 py-5 my-5 max-sm:my-0'>

                  {/* Create Post */}
              <div className='flex flex-col border-2 bg-white rounded-lg'>
                <div className='flex items-center p-5 max-sm:p-5 justify-start border-b w-full'>
                  <FaUserAlt className='mr-3 w-10 h-10 text-xl bg-slate-400 rounded-full p-2'/>
                    <input type="text" placeholder='Create post...' className='focus:outline-none bg-transparent w-80'/>
                  
                </div>
                <div className='flex items-center justify-between p-5'>
                  {/* Images */}
                  <p className='flex items-center text-purple-600'>
                    <AiOutlineCamera className='text-3xl'/>&nbsp; Image</p>
                  <p className='flex items-center text-green-500'>
                    <AiOutlineVideoCamera className='text-3xl'/>&nbsp; Video</p>
                  <p className='flex items-center text-orange-400'>
                    <BiPoll className='text-3xl'/>&nbsp; Polls</p>
                </div>
              </div>

              {/*------ Posts ----------*/}
              <div className='flex items-start justify-start shadow-lg border flex-col my-5 rounded-lg bg-white'>

                {/* User Info */}
                <div className='flex items-center p-5 w-full'>
                  <div className='flex'>
                  <FaUserAlt className='mr-3 w-10 h-10 text-xl bg-slate-400 rounded-full p-2'/>
                  <div>
                    <h3 className='font-semibold'>Mudassir</h3>
                    <p className='text-xs text-gray-400 font-semibold'>MERN developer Professional @Employee Forums</p>
                    <p className='text-xs text-gray-400 font-semibold'>6h ago </p>
                  </div>
                  </div>
                </div>
                {/* Conetnt */}
                <div className=' flex flex-col'>
                  <p className='text-sm text-gray-600 font-semibold px-5'>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Veritatis maiores magnam quas aliquam velit deleniti vel nesciunt, blanditiis, minima, nam consequuntur magni eius. Dolore natus eum vitae, voluptatem pariatur debitis obcaecati veniam sint rem placeat laudantium voluptatibus eaque quia laborum!
                  </p>

                  <div className='flex items-center justify-between py-3 px-5'>
                    <div className='flex items-center gap-4'>
                      <p className='flex items-center gap-2 text-gray-500 font-semibold'><FaThumbsUp className='text-blue-600'/>500</p>
                      <p className='text-gray-500 font-semibold'>~ 24 comments</p>
                    </div>
                    <p className='text-gray-500 font-semibold'>6.6K Views</p>
                  </div>


                  {/* comment-box */}
                  <div className='flex flex-col w-full border-t border-slate-300 p-5'>

                    <div className='flex items-center justify-between'>
                    <p className='flex items-center gap-2 text-gray-500 font-semibold'><FaThumbsUp className='text-blue-600 text-xl'/> Liked</p>
                    <p className='flex items-center gap-2 text-gray-500 font-semibold'><FaRegComment className='text-xl'/> 
                    Comment</p>
                    <p className='flex items-center gap-2 text-gray-500 font-semibold'><AiOutlineShareAlt
                    className='text-2xl'/> 
                    Share</p>
                    <p className='flex items-center gap-2 text-gray-500 font-semibold'><FiSend className='text-xl'/> 
                    Send</p>
                    </div>
                    <div className='flex items-center justify-start gap-3 pt-7 '>
                      <FaUserAlt/>
                      <div className='flex items-center justify-between border-2 border-slate-300 rounded-2xl px-3 py-1 w-11/12'>
                      <input type="text" placeholder='Type here...' className='focus:outline-none'/>
                      <BiSmile className='text-2xl'/>
                      </div>
                    </div>
                  </div>
                </div>
                
              </div>


              {/*------- Post-2 -------*/}

              <div className='flex items-start justify-start shadow-lg border flex-col bg-white'>

                {/* User Info */}
                <div className='flex items-center p-5 w-full'>
                  <div className='flex'>
                  <FaUserAlt className='mr-3 w-10 h-10 text-xl bg-slate-400 rounded-full p-2'/>
                  <div>
                    <h3 className='font-semibold'>Mudassir</h3>
                    <p className='text-xs text-gray-400 font-semibold'>MERN developer Professional @Employee Forums</p>
                    <p className='text-xs text-gray-400 font-semibold'>6h ago </p>
                  </div>
                  </div>
                </div>
                {/* Conetnt */}
                <div className=' flex flex-col'>
                  <p className='text-sm text-gray-600 font-semibold px-5'>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Veritatis maiores magnam quas aliquam velit deleniti vel nesciunt, blanditiis, minima, nam consequuntur magni eius. Dolore natus eum vitae, voluptatem pariatur debitis obcaecati veniam sint rem placeat laudantium voluptatibus eaque quia laborum!
                  </p>

                  <div className='flex items-center justify-between py-3 px-5'>
                    <div className='flex items-center gap-4'>
                      <p className='flex items-center gap-2 text-gray-500 font-semibold'><FaThumbsUp className='text-blue-600'/> 71</p>
                      <p className='text-gray-500 font-semibold'>~ 24 comments</p>
                    </div>
                    <p className='text-gray-500 font-semibold'>6.6K Views</p>
                  </div>


                  <div className='flex flex-col w-full border-t border-slate-300 p-5'>

                    <div className='flex items-center justify-between'>
                    <p className='flex items-center gap-2 text-gray-500 font-semibold'><FaThumbsUp className='text-blue-600 text-xl'/> Liked</p>
                    <p className='flex items-center gap-2 text-gray-500 font-semibold'><FaRegComment className='text-xl'/> 
                    Comment</p>
                    <p className='flex items-center gap-2 text-gray-500 font-semibold'><AiOutlineShareAlt
                    className='text-2xl'/> 
                    Share</p>
                    <p className='flex items-center gap-2 text-gray-500 font-semibold'><FiSend className='text-xl'/> 
                    Send</p>
                    </div>
                    {/*------- comment-box --------*/}
                    <div className='flex items-center justify-start gap-3 pt-7 '>
                      <FaUserAlt/>
                      <div className='flex items-center justify-between border-2 border-slate-300 rounded-2xl px-3 py-1 w-11/12'>
                      <input type="text" placeholder='Type here...' className='focus:outline-none'/>
                      <BiSmile className='text-2xl'/>
                      </div>
                    </div>

                    {/*-------- Comments --------*/}
                    <div className='flex flex-col mt-10'>
                      <div className='flex'>
                      <FaUserAlt className=' w-8 h-8 text-xl bg-slate-400 rounded-full p-2 my-3'/>
                        <div className='flex flex-col py-3 px-5 border bg-gray-200 ml-2 rounded-md flex-1'>
                          <div className='flex justify-between'>
                            <div className='flex flex-col items-start justify-start'>
                              <h4 className='text-sm font-bold'>Shiv Malhotra</h4>
                              <p className='text-gray-500 font-semibold text-xs'>Corporate Communication Professional @Employee Forums</p>
                            </div>
                            <p className='text-sm text-gray-500 pl-5'>12m</p>
                          </div>
                          <p className='pt-4 pb-1'>Great Work</p>
                        </div>
                      </div>
                        <p className='text-xs text-gray-500 font-semibold px-12 mt-2'>Like | Reply</p>
                    </div>

                    {/*---------- Comment-2 -------*/}
                    <div className='flex flex-col mt-7 pl-7'>
                      <div className='flex'>
                      <FaUserAlt className=' w-8 h-8 text-xl bg-slate-400 rounded-full p-2 my-3'/>
                        <div className='flex flex-col py-3 px-5 border bg-gray-200 ml-2 rounded-md flex-1'>
                          <div className='flex justify-between'>
                            <div className='flex flex-col items-start justify-start'>
                              <h4 className='text-sm font-bold'>Yesha Sagar</h4>
                              <p className='text-gray-500 font-semibold text-xs'>Corporate Communication Professional @Employee Forums</p>
                            </div>
                            <p className='text-sm text-gray-500 pl-5'>5m</p>
                          </div>
                          <p className='pt-4 pb-1'>Well Done !!!</p>
                        </div>
                      </div>
                        <p className='text-xs text-gray-500 font-semibold px-12 mt-2 flex items-center gap-2'>Like <FaThumbsUp className='text-blue-600'/> 7 | Reply</p>
                    </div>
                  </div>
                </div>
                
              </div>

              {/*------- Post-3 ------*/}

              <div className='flex items-start justify-start shadow-lg border flex-col my-5 rounded-lg bg-white'>

                {/* User Info */}
                <div className='flex items-center p-5 w-full'>
                  <div className='flex'>
                  <FaUserAlt className='mr-3 w-10 h-10 text-xl bg-slate-400 rounded-full p-2 my-1'/>
                  <div>
                    <h3 className='font-semibold'>Mudassir</h3>
                    <p className='text-xs text-gray-400 font-semibold'>MERN developer Professional @Employee Forums</p>
                    <p className='text-xs text-gray-400 font-semibold'>6h ago </p>
                  </div>
                  </div>
                </div>
                {/* Conetnt */}
                <div className=' flex flex-col w-full'>
                  <p className='text-md text-gray-600 font-semibold px-5'>
                    Please provide your feedback. Many Thanks!!
                  </p>
                  
              {/*---- Feedback ----*/}
                  <div className='flex items-start justify-start border border-slate-300 flex-col m-5 rounded-md bg-white'>

                {/* User Info */}
                <div className='flex items-center p-5 w-full'>
                  <div className='flex'>
                  <FaUserAlt className='mr-3 w-10 h-10 text-xl bg-slate-400 rounded-full p-2 my-1'/>
                  <div>
                    <h3 className='font-semibold'>Mudassir</h3>
                    <p className='text-xs text-gray-400 font-semibold'>MERN developer Professional @Employee Forums</p>
                    <p className='text-xs text-gray-400 font-semibold'>6h ago </p>
                  </div>
                  </div>
                </div>
                {/* Conetnt */}
                <div className=' flex flex-col'>
                  <p className='text-sm text-gray-600 font-semibold px-5 pb-3'>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Veritatis maiores magnam quas aliquam velit deleniti vel nesciunt, blanditiis, minima, nam consequuntur magni eius. Dolore natus eum vitae, voluptatem pariatur debitis obcaecati veniam sint rem placeat laudantium voluptatibus eaque quia laborum!
                  </p>

                </div>
                
              </div>

                  <div className='flex items-center justify-between py-3 px-5'>
                    <div className='flex items-center gap-4'>
                      <p className='flex items-center gap-2 text-gray-500 font-semibold'><FaThumbsUp className='text-blue-600'/> 0</p>
                      <p className='text-gray-500 font-semibold'>~ 0 comments</p>
                    </div>
                    <p className='text-gray-500 font-semibold'>6.6K Views</p>
                  </div>


                  {/* comment-box */}
                  <div className='flex flex-col w-full border-t border-slate-300 p-5'>

                    <div className='flex items-center justify-between'>
                    <p className='flex items-center gap-2 text-gray-500 font-semibold'><FaThumbsUp className=' text-xl'/> Liked</p>
                    <p className='flex items-center gap-2 text-gray-500 font-semibold'><FaRegComment className='text-xl'/> 
                    Comment</p>
                    <p className='flex items-center gap-2 text-gray-500 font-semibold'><AiOutlineShareAlt
                    className='text-2xl'/> 
                    Share</p>
                    <p className='flex items-center gap-2 text-gray-500 font-semibold'><FiSend className='text-xl'/> 
                    Send</p>
                    </div>
                    
                  </div>
                </div>
                
              </div>
            </div>

            {/* -------- 3 Column ---------*/}
            <div className='mx-4 max-sm:w-6/12 max-sm:pb-20'>
              
                <div className='flex flex-col my-10 px-2 shadow-lg border-2 rounded-lg bg-slate-50'>
                <div className='flex flex-col'>
                  <h4 className='text-lg font-semibold py-3 px-4'>People you may know</h4>
                  <div>
                  {/* Users */}
                  <div className='flex items-center gap-5 pl-4 mt-3 max-sm:gap-7'>
                    <FaUserAlt className='text-2xl'/>
                    <div>
                      <h4 className='text-lg font-semibold'>Preeti</h4>
                      <p className='text-xs text-gray-400 font-semibold'>UI/UX Developer</p>
                    </div>
                    <AiOutlineUsergroupAdd className='cursor-pointer text-3xl text-blue-500 ml-5'/>
                  </div>

                  {/* Users */}
                  <div className='flex items-center gap-5 pl-4 mt-3 max-sm:gap-7'>
                    <FaUserAlt className='text-2xl'/>
                    <div>
                      <h4 className='text-lg font-semibold'>Preeti</h4>
                      <p className='text-xs text-gray-400 font-semibold'>UI/UX Developer</p>
                    </div>
                    <AiOutlineUsergroupAdd className='cursor-pointer text-3xl text-blue-500 ml-5'/>
                  </div>

                  {/* Users */}
                  <div className='flex items-center gap-5 pl-4 mt-3 max-sm:gap-7'>
                    <FaUserAlt className='text-2xl'/>
                    <div>
                      <h4 className='text-lg font-semibold'>Preeti</h4>
                      <p className='text-xs text-gray-400 font-semibold'>UI/UX Developer</p>
                    </div>
                    <AiOutlineUsergroupAdd className='cursor-pointer text-3xl text-blue-500 ml-5'/>
                  </div>

                  {/* Users */}
                  <div className='flex items-center gap-5 pl-4 mt-3 pb-3 max-sm:gap-7'>
                    <FaUserAlt className='text-2xl'/>
                    <div>
                      <h4 className='text-lg font-semibold'>Preeti</h4>
                      <p className='text-xs text-gray-400 font-semibold'>UI/UX Developer</p>
                    </div>
                    <AiOutlineUsergroupAdd className='cursor-pointer text-3xl text-blue-500 ml-5'/>
                  </div>

                </div>
              </div>
                <div className='flex items-center justify-center border-t-2 p-4'>
                  <p className='text-blue-500 mr-2 font-semibold'>View All</p>
                </div>

                </div>
              
            </div>
          </div>
        </div>
        
      </main>
      
    </div>
  )
}
