import Head from 'next/head'
import Sidenav from './Sidenav'
import Nav from './Nav'
import Bottomnav from './BottomNav'
import Main from './Main'



export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='flex'>
        <Sidenav/>

        <div className='flex-1'>
          <Nav/>
          <Main/>
          <Bottomnav/>
        </div> 
      </main>
      
    </div>
  )
}
